### ISSUE TITLE
Dragging reticle outside of picker container causes it to close

### ISSUE THREAD

**Issue by jbalboni** [bgrins/spectrum#249] opened 2014-09-02 21:07 UTC
Steps:

1. Open picker.
2. Click and drag reticle in any direction until your mouse pointer is outside the picker container.
3. Release the mouse button
4. The color picker closes

I don't think this is common, but a designer ran into it when testing out a page I made. It would be nice if releasing the mouse button outside the picker didn't close it.

Thanks for the plugin! It's working well for us overall.

**Comment by soundar24** [comment] 2015-01-04 18:27
Regarding this issue i can able to understand the cause. But i want to let you know about the color picker behavior. 
In general when a popup is opened in a page, it should be closed while mousedown on the document (not in click).

In any HTML page just right click on the mouse, it opens the context menu popup. It also closed while mousedown in any position in the document.

Check the reference with default select element: http://jsfiddle.net/soundar24/ctkY3/3134/
If the behavior is changed like that, then it may solved.

**Comment by bgrins** [comment] 2015-01-05 17:44
I see this, it should close on mousedown.  I'll see if changing it to this behavior would fix the problem with dragging and releasing the mouse

**Comment by bgrins** [comment] 2015-03-21 05:06
This is a high priority bug blocking a 2.0 release

**Comment by bgrins** [comment] 2015-04-27 03:26
Just pushed https://github.com/bgrins/spectrum/commit/df7a8af637b7c5d565a9f46d3568d7c06fd23c3e, which fixes this.  I'll include it in the 1.7 release

**Comment by bgrins** [comment] 2015-04-27 04:16
This has been released in 1.7.0: https://github.com/bgrins/spectrum/releases/tag/1.7.0

**Closed by bgrins** 2015-04-27 04:16 UTC
Labels: blocks-2.0
